eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
spring:
  application:
    name: zuul-service
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    api-a:
      path: /api-code/**
      serviceId: THE-CODE-SERVICE
    api-b:
      path: /api-json/**
      serviceId: THE-JSON-SERVICE
    api-c:
      path: /api-data/**
      serviceId: DATA-SERVICE
